trigger: none
pool: TestPool

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: CopyFiles@2
  displayName: 'Copy Java source files'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*.java'
    TargetFolder: '$(Build.BinariesDirectory)'

- task: CopyFiles@2
  displayName: 'Copy JAR library'
  inputs:
    SourceFolder: './Generator/'
    Contents: '*.jar'
    TargetFolder: '$(Build.BinariesDirectory)/lib'

- task: CmdLine@2
  displayName: 'Compile Java code'
  inputs:
    script: 'javac -cp "$(Build.BinariesDirectory)/lib/*" -d $(Build.BinariesDirectory) $(Build.BinariesDirectory)/*.java'

- task: CmdLine@2
  displayName: 'Execute Java program'
  inputs:
    script: 'java -cp "$(Build.BinariesDirectory)/lib/*:$(Build.BinariesDirectory)" YourClassName'

- task: PublishPipelineArtifact@1
  displayName: 'Publish artifact'
  inputs:
    targetPath: '$(Build.BinariesDirectory)/*.txt'
    artifact: 'result-artifact'
