trigger: none
pool: TestPool

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8'
    jdkArchitecture: 'x64'

- task: CopyFiles@2
  displayName: 'Copy JAR file'
  inputs:
    SourceFolder: 'Generator/lib'
    Contents: 'mssql-jdbc-12.2.0.jre8.jar'
    TargetFolder: '$(Build.BinariesDirectory)/lib'

- task: CopyFiles@2
  displayName: 'Copy source files'
  inputs:
    SourceFolder: 'Generator/src'
    Contents: '**/*.java'
    TargetFolder: '$(Build.BinariesDirectory)/src'

- task: Maven@3
  displayName: 'Maven Install'
  inputs:
    mavenPomFile: 'Generator/pom.xml'
    mavenOptions: '-DskipTests=true'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'clean package'

- task: CmdLine@2
  displayName: 'Execute Java program'
  inputs:
    script: 'java -cp "$(Build.BinariesDirectory)/lib/*:$(Build.BinariesDirectory)/target/*" CodeGenerator'

- task: PublishPipelineArtifact@1
  displayName: 'Publish artifact'
  inputs:
    targetPath: '$(Build.BinariesDirectory)/target/*.txt'
    artifact: 'result-artifact'